<a href="https://colab.research.google.com/github/angelmercy2310-beep/SkillsQuark-DataScience-Internship/blob/main/Task%201%20-%20Data%20Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

print("Task 1 - Data Manipulation")
print("Notebook is ready!")

Pandas version: 2.2.3
NumPy version: 2.1.3
Task 1 - Data Manipulation
Notebook is ready!

In [2]:
import pandas as pd
import numpy as np

data = {
    "Customer_ID": [101, 102, 103, 104, 105, 106, 106, 108, 109, 110],
    "Name": ["Anu", "Bala", "Charu", "Deepa", "Ezhil",
             "Farah", "Farah", "Hari", "Isha", "Jaya"],
    "Age": [22, 25, np.nan, 28, 30, 24, 24, np.nan, 27, 32],
    "City": ["Chennai", "Madurai", "Chennai", "Trichy", np.nan,
             "Salem", "Salem", "Chennai", "Madurai", "Trichy"],
    "Purchase_Amount": [1500, 2500, 1800, np.nan, 3200,
                        2100, 2100, 1700, np.nan, 4000]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

print("Dataset Shape:", df.shape)
print("Missing Values:")
print(df.isnull().sum())

Original Dataset:

   Customer_ID   Name   Age     City  Purchase_Amount
0          101    Anu  22.0  Chennai           1500.0
1          102   Bala  25.0  Madurai           2500.0
2          103  Charu   NaN  Chennai           1800.0
3          104  Deepa  28.0   Trichy              NaN
4          105  Ezhil  30.0      NaN           3200.0
5          106  Farah  24.0    Salem           2100.0
6          106  Farah  24.0    Salem           2100.0
7          108   Hari   NaN  Chennai           1700.0
8          109   Isha  27.0  Madurai              NaN
9          110   Jaya  32.0   Trichy           4000.0

Dataset Shape: (10, 5)
Missing Values:
Customer_ID        0
Name               0
Age                2
City               1
Purchase_Amount    2
dtype: int64

In [3]:
# Remove duplicate records
df = df.drop_duplicates()

print("Dataset after removing duplicates:")
display(df)

print("Updated Dataset Shape:", df.shape)
print("Duplicate records remaining:", df.duplicated().sum())

Dataset after removing duplicates:

   Customer_ID   Name   Age     City  Purchase_Amount
0          101    Anu  22.0  Chennai           1500.0
1          102   Bala  25.0  Madurai           2500.0
2          103  Charu   NaN  Chennai           1800.0
3          104  Deepa  28.0   Trichy              NaN
4          105  Ezhil  30.0      NaN           3200.0
5          106  Farah  24.0    Salem           2100.0
7          108   Hari   NaN  Chennai           1700.0
8          109   Isha  27.0  Madurai              NaN
9          110   Jaya  32.0   Trichy           4000.0

Updated Dataset Shape: (9, 5)
Duplicate records remaining: 0

In [4]:
# Fill missing Age with the median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing City with the most frequent city
df["City"] = df["City"].fillna(df["City"].mode()[0])

# Fill missing Purchase_Amount with the median
df["Purchase_Amount"] = df["Purchase_Amount"].fillna(
    df["Purchase_Amount"].median()
)

print("Dataset after filling missing values:")
display(df)

print("\nMissing values remaining:")
print(df.isnull().sum())

Dataset after filling missing values:

   Customer_ID   Name   Age     City  Purchase_Amount
0          101    Anu  22.0  Chennai           1500.0
1          102   Bala  25.0  Madurai           2500.0
2          103  Charu  27.0  Chennai           1800.0
3          104  Deepa  28.0   Trichy           2100.0
4          105  Ezhil  30.0  Chennai           3200.0
5          106  Farah  24.0    Salem           2100.0
7          108   Hari  27.0  Chennai           1700.0
8          109   Isha  27.0  Madurai           2100.0
9          110   Jaya  32.0   Trichy           4000.0

Missing values remaining:
Customer_ID        0
Name               0
Age                0
City               0
Purchase_Amount    0
dtype: int64

In [5]:
# Convert Age into integer format
df["Age"] = df["Age"].astype(int)

# Create a new column for customer age group
df["Age_Group"] = df["Age"].apply(
    lambda age: "Young" if age < 25
    else "Adult" if age <= 30
    else "Senior"
)

# Create a new column with a 10% discount
df["Discount_Amount"] = df["Purchase_Amount"] * 0.10

print("Dataset after column transformation:")
display(df)

print("Updated columns:")
print(df.columns.tolist())

Dataset after column transformation:

,Customer_ID,Name,Age,City,Purchase_Amount,Age_Group,Discount_Amount
0,101,Anu,22,Chennai,1500.0,Young,150.0
1,102,Bala,25,Madurai,2500.0,Adult,250.0
2,103,Charu,27,Chennai,1800.0,Adult,180.0
3,104,Deepa,28,Trichy,2100.0,Adult,210.0
4,105,Ezhil,30,Chennai,3200.0,Adult,320.0
5,106,Farah,24,Salem,2100.0,Young,210.0
7,108,Hari,27,Chennai,1700.0,Adult,170.0
8,109,Isha,27,Madurai,2100.0,Adult,210.0
9,110,Jaya,32,Trichy,4000.0,Senior,400.0

Updated columns:
['Customer_ID', 'Name', 'Age', 'City', 'Purchase_Amount', 'Age_Group', 'Discount_Amount']

In [6]:
print("Final Dataset Information")
print("-------------------------")

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate records:", df.duplicated().sum())

print("\nStatistical Summary:")
display(df.describe())

Final Dataset Information
-------------------------
Number of rows: 9
Number of columns: 7

Missing values:
Customer_ID        0
Name               0
Age                0
City               0
Purchase_Amount    0
Age_Group          0
Discount_Amount    0
dtype: int64

Duplicate records: 0

Statistical Summary:

       Customer_ID        Age  Purchase_Amount  Discount_Amount
count     9.000000   9.000000         9.000000         9.000000
mean    105.333333  26.888889      2333.333333       233.333333
std       3.162278   3.018462       798.435971        79.843597
min     101.000000  22.000000      1500.000000       150.000000
25%     103.000000  25.000000      1800.000000       180.000000
50%     105.000000  27.000000      2100.000000       210.000000
75%     108.000000  28.000000      2500.000000       250.000000
max     110.000000  32.000000      4000.000000       400.000000

In [7]:
# Save the cleaned dataset as a CSV file
df.to_csv("Cleaned_Customer_Data.csv", index=False)

print("Cleaned dataset saved successfully!")
print("Final dataset shape:", df.shape)

display(df.head())

Cleaned dataset saved successfully!
Final dataset shape: (9, 7)

,Customer_ID,Name,Age,City,Purchase_Amount,Age_Group,Discount_Amount
0,101,Anu,22,Chennai,1500.0,Young,150.0
1,102,Bala,25,Madurai,2500.0,Adult,250.0
2,103,Charu,27,Chennai,1800.0,Adult,180.0
3,104,Deepa,28,Trichy,2100.0,Adult,210.0
4,105,Ezhil,30,Chennai,3200.0,Adult,320.0

In [8]:
from google.colab import files

files.download("Cleaned_Customer_Data.csv")